import React, { Component } from "react";

const folder = window.location.href.split("#")[0];

export const APP_CONFIG = {
  helpCenter: "https://help.simpletexting.com/en/collections/2110969-free-sms-tools",
  isFullFontsList: false,
  isTooltipsCanHide: false,
  fonts: [
    { value: "Alegreya", label: "Alegreya" },
    { value: "BioRhyme", label: "BioRhyme" },
    { value: "Crimson Text", label: "Crimson Text" },
    { value: "Fira Sans", label: "Fira Sans" },
    { value: "Libre Baskerville", label: "Libre Baskerville" },
    { value: "Lora", label: "Lora" },
    { value: "Montserrat", label: "Montserrat" },
    { value: "Open Sans", label: "Open Sans" },
    { value: "Playfair Display", label: "Playfair Display" },
    { value: "Poppins", label: "Poppins" },
    { value: "PT Sans", label: "PT Sans" },
    { value: "PT Serif", label: "PT Serif" },
    { value: "Roboto", label: "Roboto" },
    { value: "Roboto Slab", label: "Roboto Slab" },
    { value: "Rounded Mplus 1c", label: "Rounded Mplus 1c" },
    { value: "Rubik", label: "Rubik" },
    { value: "Source Serif Pro", label: "Source Serif Pro" },
    { value: "Varela Round", label: "Varela Round" },
  ],
  defaultData: {
    isPowered: true,
    folder: folder,
    size: 32,
    color: '#0068B8',
    font: 'Open Sans',
    reason: 'Text DEMO to 555888',
    reasonAlign: 'center',
    reasonWeight: 'bold',
    reasonItalic: '',
    secondarySize: 20,
    secondaryFont: 'Rubik',
    secondaryColor: '#75849C',
    secondaryReason: 'We’ll send you a quick video that shows you how to use this tool to grow your subscriber list.',
    secondaryReasonAlign: 'center',
    secondaryReasonWeight: '',
    secondaryReasonItalic: '',
    company: 'Your Company Name',
    estimated: 4,
    email: 'email@domain.com',
    customPrivacy: false,
    terms: '',
    privacy: '',
    complianceFont: 'Rubik',
    complianceSize: 14,
    complianceColor: '#75849c',
    complianceAlign: 'left',
    complianceWeight: '',
    complianceItalic: '',
    logo: folder+'assets/templates/CTA-SimpleTexting_logo.png',
    logoStyle: 'boxed',
    logoAlign: 'center',
    logoMaxWidth: 192,
    hyperlink: '',
    image: folder+'assets/templates/CTA-SimpleTexting_hero.png',
    imageWidth: 500,
    imageAlign: 'center',
    imageStyle: 'boxed',
    position: 'cta-boxed',
    colorA: '#75849C',
    stroke: '',
    background: '#FFFFFF',
    corner: 8,
    shadow: '0px 16px 64px rgba(0,0,0,0.08)',
    fontA: 'Rubik',
    sizeA: 16,
    width: 500,
    closePosition: "cta-close-tr",
    keyword: '',
    phone: '',
    shortTerms: '',
    shortTermsPrivacy: '',
    shortPrivacy: '',

    mainButtonFont: 'Rubik',
    mainButtonFontColor: '#333333',
    mainButtonFontSize: 16,
    mainButtonAlign: "center",
    mainButtonWeight: '',
    mainButtonItalic: '',
    mainButtonShadow: '0px 0px 0px rgba(0,0,0,0.0)',
    mainButtonCorner: 8,
    mainButtonStroke: "#e0e3e9",
    mainButtonBackground: "#eff3f6",
    mainButtonLabel: "",
    mainButtonType: "cta-label-texticonl",
    mainButtonIcon: "pack-message-circle",

    triggerButtonFont: 'Rubik',
    triggerButtonFontColor: '#333333',
    triggerButtonFontSize: 16,
    triggerButtonAlign: "right",
    triggerButtonWeight: '',
    triggerButtonItalic: '',
    triggerButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    triggerButtonCorner: 8,
    triggerButtonStroke: "#e0e3e9",
    triggerButtonBackground: "#eff3f6",
    triggerButtonLabel: "",
    triggerButtonType: "cta-label-texticonl",
    triggerButtonIcon: "pack-message-circle",

    textUsButtonNumber: '555888',
    textUsButtonText: '',
    textUsButtonFont: 'Rubik',
    textUsButtonFontColor: '#333333',
    textUsButtonFontSize: 16,
    textUsButtonAlign: "right",
    textUsButtonWeight: '',
    textUsButtonItalic: '',
    textUsButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    textUsButtonCorner: 8,
    textUsButtonStroke: "#e0e3e9",
    textUsButtonBackground: "#eff3f6",
    textUsButtonLabel: "",
    textUsButtonType: "cta-label-textonly",
    textUsButtonIcon: ""
  }
}

export const getInitialData = () => {
  const defaultData = {
    isPowered: true,
    folder: window.location.href,
    size: 22,
    color: '#333333',
    font: 'PT Sans',
    reason: '',
    reasonAlign: 'left',
    reasonWeight: '',
    reasonItalic: '',
    secondarySize: 15,
    secondaryFont: 'PT Sans',
    secondaryColor: '#333333',
    secondaryReason: '',
    secondaryReasonAlign: 'left',
    secondaryReasonWeight: '',
    secondaryReasonItalic: '',
    company: 'Your Company Name',
    estimated: 4,
    email: 'email@domain.com',
    customPrivacy: false,
    terms: '',
    privacy: '',
    complianceFont: 'PT Sans',
    complianceSize: 10,
    complianceColor: '#75849c',
    complianceAlign: 'left',
    complianceWeight: '',
    complianceItalic: '',
    logo: '',
    logoStyle: 'boxed',
    logoAlign: 'left',
    logoMaxWidth: 45,
    hyperlink: '',
    image: 'http://',
    imageWidth: 300,
    imageAlign: 'center',
    imageStyle: 'boxed',
    position: 'cta-boxed',
    colorA: '#75849C',
    stroke: '',
    background: '#FFFFFF',
    corner: 8,
    shadow: '0px 16px 64px rgba(0,0,0,0.08)',
    fontA: 'PT Sans',
    sizeA: 16,
    width: 500,
    closePosition: "cta-close-tr",
    keyword: '',
    phone: '',
    shortTerms: '',
    shortTermsPrivacy: '',
    shortPrivacy: '',

    mainButtonFont: 'PT Sans',
    mainButtonFontColor: '#333333',
    mainButtonFontSize: 16,
    mainButtonAlign: "center",
    mainButtonWeight: '',
    mainButtonItalic: '',
    mainButtonShadow: '0px 0px 0px rgba(0,0,0,0.0)',
    mainButtonCorner: 8,
    mainButtonStroke: "#e0e3e9",
    mainButtonBackground: "#eff3f6",
    mainButtonLabel: "Button",
    mainButtonType: "cta-label-texticonl",
    mainButtonIcon: "pack-message-circle",

    triggerButtonFont: 'PT Sans',
    triggerButtonFontColor: '#333333',
    triggerButtonFontSize: 16,
    triggerButtonAlign: "right",
    triggerButtonWeight: '',
    triggerButtonItalic: '',
    triggerButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    triggerButtonCorner: 8,
    triggerButtonStroke: "#e0e3e9",
    triggerButtonBackground: "#eff3f6",
    triggerButtonLabel: "Button",
    triggerButtonType: "cta-label-texticonl",
    triggerButtonIcon: "pack-message-circle",

    textUsButtonNumber: '555888',
    textUsButtonText: '',
    textUsButtonFont: 'PT Sans',
    textUsButtonFontColor: '#333333',
    textUsButtonFontSize: 16,
    textUsButtonAlign: "right",
    textUsButtonWeight: '',
    textUsButtonItalic: '',
    textUsButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    textUsButtonCorner: 8,
    textUsButtonStroke: "#e0e3e9",
    textUsButtonBackground: "#eff3f6",
    textUsButtonLabel: "Button",
    textUsButtonType: "cta-label-textonly",
    textUsButtonIcon: ""
  };
  return defaultData;
}

export const services = {
  shortLinksKey: "AIzaSyA8Nm6oDG9n620UdTHfXww3xhBtW2yekq8",
  shortLinksDomain: "https://txturl.io"
}

export const LAYOUT_NAMES = [
  'Sign-Up Graphics',
  'Mobile Sign-Up Widget (Popup)',
  'Click-to-Text Button',
];

export const SWATCHES = [
  'rgba(255, 255, 255, 1)',
  'rgba(0, 0, 0, 1)',
  'rgba(244, 67, 54, 1)',
  'rgba(233, 30, 99, 1)',
  'rgba(156, 39, 176, 1)',
  'rgba(103, 58, 183, 1)',
  'rgba(63, 81, 181, 1)',
  'rgba(33, 150, 243, 1)',
  'rgba(3, 169, 244, 1)',
  'rgba(0, 188, 212, 1)',
  'rgba(0, 150, 136, 1)',
  'rgba(76, 175, 80, 1)',
  'rgba(139, 195, 74, 1)',
  'rgba(205, 220, 57, 1)',
  'rgba(255, 235, 59, 1)',
  'rgba(255, 193, 7, 1)'
]

export const SHADOWS = [
  { shadow: '0px 16px 64px rgba(0,0,0,0.08)', class: '' },
  { shadow: '0px 0px 0px rgba(0,0,0,0.0)', class: 'no-shadow' },
  { shadow: '0px 10px 30px rgba(0,0,0,0.08)', class: '' },
  { shadow: '0px 5px 10px rgba(0,0,0,0.08)', class: '' },
  { shadow: '0px 5px 20px rgba(0,0,0,0.2)', class: '' },
  { shadow: '0px 2px 5px rgba(0,0,0,0.8)', class: '' },
]

export const CLOSE_POSITIONS = [
  { label: 'top-left', value: 'cta-close-tl' },
  { label: 'top-right', value: 'cta-close-tr' },
]

export const BEHAVIOR_POSITIONS = [
  { label: 'bottom-right', value: 'cta-position-br' },
  { label: 'bottom-center', value: 'cta-position-bc' },
  { label: 'bottom-left', value: 'cta-position-bl' },
]

export const BUTTONS_TYPES = [
  { label: 'Text only', value: 'cta-label-textonly', icon: <i className="icon-text-only"></i> },
  { label: 'Text +  icon left', value: 'cta-label-texticonl', icon: <i className="icon-text-icon-left"></i> },
  { label: 'Text +  icon right', value: 'cta-label-texticonr', icon: <i className="icon-text-icon-right"></i> },
]

export const PICKR_CONFIG = {
  COMPONENTS: {
    preview: true,
    opacity: true,
    hue: true,

    interaction: {
      input: true,
      clear: true,
      save: true
    }
  },
  THEME: "monolith",
  SAVE: { save: 'Save' }
}

export const ICON_PACK = [
  "pack-type",
  "pack-umbrella",
  "pack-underline",
  "pack-unlock",
  "pack-upload",
  "pack-upload-cloud",
  "pack-user",
  "pack-user-check",
  "pack-user-minus",
  "pack-user-plus",
  "pack-users",
  "pack-user-x",
  "pack-video",
  "pack-video-off",
  "pack-voicemail",
  "pack-volume",
  "pack-volume-1",
  "pack-volume-2",
  "pack-volume-x",
  "pack-watch",
  "pack-wifi",
  "pack-wifi-off",
  "pack-wind",
  "pack-x",
  "pack-x-circle",
  "pack-x-square",
  "pack-youtube",
  "pack-zap",
  "pack-zap-off",
  "pack-zoom-in",
  "pack-zoom-out",
  "pack-activity",
  "pack-airplay",
  "pack-alert-circle",
  "pack-alert-octagon",
  "pack-alert-triangle",
  "pack-align-center",
  "pack-align-justify",
  "pack-align-left",
  "pack-align-right",
  "pack-anchor",
  "pack-announcement-speaker",
  "pack-aperture",
  "pack-archive",
  "pack-arrow-down",
  "pack-arrow-down-circle",
  "pack-arrow-down-left",
  "pack-arrow-down-right",
  "pack-arrow-left",
  "pack-arrow-left-circle",
  "pack-arrow-right",
  "pack-arrow-right-circle",
  "pack-arrow-up",
  "pack-arrow-up-circle",
  "pack-arrow-up-left",
  "pack-arrow-up-right",
  "pack-at-sign",
  "pack-award",
  "pack-bar-chart",
  "pack-bar-chart-2",
  "pack-battery",
  "pack-battery-charging",
  "pack-bell",
  "pack-bell-off",
  "pack-bluetooth",
  "pack-bold",
  "pack-book",
  "pack-bookmark",
  "pack-book-open",
  "pack-box",
  "pack-briefcase",
  "pack-calendar",
  "pack-camera",
  "pack-camera-off",
  "pack-carret---down",
  "pack-carret---left",
  "pack-carret---right",
  "pack-carret---up",
  "pack-cast",
  "pack-check",
  "pack-check-circle",
  "pack-check-square",
  "pack-chevron-down",
  "pack-chevron-left",
  "pack-chevron-right",
  "pack-chevrons-down",
  "pack-chevrons-left",
  "pack-chevrons-right",
  "pack-chevrons-up",
  "pack-chevron-up",
  "pack-chrome",
  "pack-circle",
  "pack-clipboard",
  "pack-clock",
  "pack-cloud-drizzle",
  "pack-cloud-lightning",
  "pack-cloud-off",
  "pack-cloud-rain",
  "pack-cloud-snow",
  "pack-code",
  "pack-codepen",
  "pack-command",
  "pack-compass",
  "pack-copy",
  "pack-corner-down-left",
  "pack-corner-down-right",
  "pack-corner-left-down",
  "pack-corner-left-up",
  "pack-corner-right-down",
  "pack-corner-right-up",
  "pack-corner-up-left",
  "pack-corner-up-right",
  "pack-cpu",
  "pack-credit-card",
  "pack-crop",
  "pack-crosshair",
  "pack-database",
  "pack-delete",
  "pack-disc",
  "pack-dollar-sign",
  "pack-download",
  "pack-download-cloud",
  "pack-droplet",
  "pack-edit",
  "pack-edit-2",
  "pack-edit-3",
  "pack-external-link",
  "pack-eye",
  "pack-eye-off",
  "pack-facebook",
  "pack-fast-forward",
  "pack-feather",
  "pack-file",
  "pack-file-minus",
  "pack-file-plus",
  "pack-file-text",
  "pack-film",
  "pack-filter",
  "pack-flag",
  "pack-folder",
  "pack-folder-minus",
  "pack-folder-plus",
  "pack-gift",
  "pack-git-branch",
  "pack-git-commit",
  "pack-github",
  "pack-gitlab",
  "pack-git-merge",
  "pack-git-pull-request",
  "pack-globe",
  "pack-grid",
  "pack-hard-drive",
  "pack-hash",
  "pack-headphones",
  "pack-heart",
  "pack-help-circle",
  "pack-home",
  "pack-image",
  "pack-inbox",
  "pack-info",
  "pack-instagram",
  "pack-intercom-icon",
  "pack-italic",
  "pack-layers",
  "pack-layout",
  "pack-life-buoy-help",
  "pack-link",
  "pack-link-2",
  "pack-linkedin",
  "pack-list",
  "pack-live-support-agent-headset",
  "pack-loader",
  "pack-lock",
  "pack-log-in",
  "pack-log-out",
  "pack-mail",
  "pack-map",
  "pack-map-pin",
  "pack-maximize",
  "pack-maximize-2",
  "pack-menu",
  "pack-message-circle",
  "pack-message-square",
  "pack-mic",
  "pack-mic-off",
  "pack-minimize",
  "pack-minimize-2",
  "pack-minus",
  "pack-minus-circle",
  "pack-minus-square",
  "pack-monitor",
  "pack-moon",
  "pack-more-horizontal",
  "pack-more-vertical",
  "pack-move",
  "pack-music",
  "pack-navigation",
  "pack-navigation-2",
  "pack-octagon",
  "pack-package",
  "pack-paperclip",
  "pack-pause",
  "pack-pause-circle",
  "pack-percent",
  "pack-phone-chat-message-sms",
  "pack-phone-call",
  "pack-phone-forwarded",
  "pack-phone-incoming-2",
  "pack-phone-missed",
  "pack-phone-off",
  "pack-phone-outgoing",
  "pack-pie-chart",
  "pack-play",
  "pack-play-circle",
  "pack-plug",
  "pack-plus",
  "pack-plus-circle",
  "pack-plus-square",
  "pack-pocket",
  "pack-power",
  "pack-printer",
  "pack-radio",
  "pack-refresh-ccw",
  "pack-refresh-cw",
  "pack-repeat",
  "pack-rewind",
  "pack-rotate-ccw",
  "pack-rotate-cw",
  "pack-rss",
  "pack-save",
  "pack-scissors",
  "pack-search",
  "pack-send",
  "pack-server",
  "pack-settings",
  "pack-share",
  "pack-share-2",
  "pack-shield",
  "pack-shield-off",
  "pack-shopping-bag",
  "pack-shopping-cart",
  "pack-shuffle",
  "pack-sidebar",
  "pack-skip-back",
  "pack-skip-forward",
  "pack-slack",
  "pack-slash",
  "pack-sliders",
  "pack-smartphone",
  "pack-speaker",
  "pack-square",
  "pack-star",
  "pack-stop-circle",
  "pack-sun",
  "pack-sunrise",
  "pack-sunset",
  "pack-tablet",
  "pack-tag",
  "pack-target",
  "pack-terminal",
  "pack-thermometer",
  "pack-thumbs-down",
  "pack-thumbs-up",
  "pack-toggle-left",
  "pack-toggle-right",
  "pack-trash",
  "pack-trash-2",
  "pack-trending-down",
  "pack-trending-up",
  "pack-triangle",
  "pack-truck",
  "pack-tv",
  "pack-twitter"
]

export const TEMPLATES = [
  {
    isPowered: true,
    folder: folder,
    size: 32,
    color: '#EC397B',
    font: 'Fira Sans',
    reason: 'Text RUN to 900900 to sign up for discounts',
    reasonAlign: 'center',
    reasonWeight: 'bold',
    reasonItalic: 'italic',
    secondarySize: 22,
    secondaryFont: 'Fira Sans',
    secondaryColor: '#4A4E85',
    secondaryReason: 'We’ll text you an exclusive offer every Monday so you can start your week on the right foot!',
    secondaryReasonAlign: 'center',
    secondaryReasonWeight: '',
    secondaryReasonItalic: '',
    company: 'Your Company Name',
    estimated: 4,
    email: 'email@domain.com',
    customPrivacy: false,
    terms: '',
    privacy: '',
    complianceFont: 'Fira Sans',
    complianceSize: 14,
    complianceColor: '#75849c',
    complianceAlign: 'left',
    complianceWeight: '',
    complianceItalic: '',
    logo: folder+'assets/templates/Fitness_logo.svg',
    logoStyle: 'boxed',
    logoAlign: 'center',
    logoMaxWidth: 68,
    hyperlink: '',
    image: folder+'assets/templates/Fitness_hero.png',
    imageWidth: 500,
    imageAlign: 'center',
    imageStyle: 'boxed',
    position: 'cta-boxed',
    colorA: '#75849C',
    stroke: '',
    background: '#FFFFFF',
    corner: 8,
    shadow: '0px 16px 64px rgba(0,0,0,0.08)',
    fontA: 'Fira Sans',
    sizeA: 16,
    width: 500,
    closePosition: "cta-close-tr",
    keyword: '',
    phone: '',
    shortTerms: '',
    shortTermsPrivacy: '',
    shortPrivacy: '',

    mainButtonFont: 'Fira Sans',
    mainButtonFontColor: '#333333',
    mainButtonFontSize: 16,
    mainButtonAlign: "center",
    mainButtonWeight: '',
    mainButtonItalic: '',
    mainButtonShadow: '0px 0px 0px rgba(0,0,0,0.0)',
    mainButtonCorner: 8,
    mainButtonStroke: "#e0e3e9",
    mainButtonBackground: "transparent",
    mainButtonLabel: "Sign up today",
    mainButtonType: "cta-label-texticonl",
    mainButtonIcon: "pack-message-circle",

    triggerButtonFont: 'Fira Sans',
    triggerButtonFontColor: '#333333',
    triggerButtonFontSize: 16,
    triggerButtonAlign: "right",
    triggerButtonWeight: '',
    triggerButtonItalic: '',
    triggerButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    triggerButtonCorner: 8,
    triggerButtonStroke: "#e0e3e9",
    triggerButtonBackground: "#eff3f6",
    triggerButtonLabel: "Click here for exclusive discounts",
    triggerButtonType: "cta-label-texticonl",
    triggerButtonIcon: "pack-message-circle",

    textUsButtonNumber: '555888',
    textUsButtonText: '',
    textUsButtonFont: 'Fira Sans',
    textUsButtonFontColor: '#333333',
    textUsButtonFontSize: 16,
    textUsButtonAlign: "right",
    textUsButtonWeight: '',
    textUsButtonItalic: '',
    textUsButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    textUsButtonCorner: 8,
    textUsButtonStroke: "#e0e3e9",
    textUsButtonBackground: "transparent",
    textUsButtonLabel: "Click here for exclusive discounts",
    textUsButtonType: "cta-label-textonly",
    textUsButtonIcon: ""
  },
  {
    isPowered: true,
    folder: folder,
    size: 32,
    color: '#0E7692',
    font: 'Varela Round',
    reason: 'Text TECHTIME to 900900 for 10% off your order',
    reasonAlign: 'center',
    reasonWeight: '',
    reasonItalic: '',
    secondarySize: 22,
    secondaryFont: 'Varela Round',
    secondaryColor: '#58666D',
    secondaryReason: 'You’ll receive a unique discount code and be signed up for weekly discounts on all your favorite products.',
    secondaryReasonAlign: 'center',
    secondaryReasonWeight: '',
    secondaryReasonItalic: '',
    company: 'Your Company Name',
    estimated: 4,
    email: 'email@domain.com',
    customPrivacy: false,
    terms: '',
    privacy: '',
    complianceFont: 'Varela Round',
    complianceSize: 14,
    complianceColor: '#75849c',
    complianceAlign: 'left',
    complianceWeight: '',
    complianceItalic: '',
    logo: folder+'assets/templates/Ecommerce1_logo.png',
    logoStyle: 'boxed',
    logoAlign: 'center',
    logoMaxWidth: 84,
    hyperlink: '',
    image: folder+'assets/templates/AgLMrojqjAM.png',
    imageWidth: 500,
    imageAlign: 'center',
    imageStyle: 'boxed',
    position: 'cta-boxed',
    colorA: '#75849C',
    stroke: '',
    background: '#FFFFFF',
    corner: 8,
    shadow: '0px 16px 64px rgba(0,0,0,0.08)',
    fontA: 'Varela Round',
    sizeA: 16,
    width: 500,
    closePosition: "cta-close-tr",
    keyword: '',
    phone: '',
    shortTerms: '',
    shortTermsPrivacy: '',
    shortPrivacy: '',

    mainButtonFont: 'Varela Round',
    mainButtonFontColor: '#333333',
    mainButtonFontSize: 16,
    mainButtonAlign: "center",
    mainButtonWeight: '',
    mainButtonItalic: '',
    mainButtonShadow: '0px 0px 0px rgba(0,0,0,0.0)',
    mainButtonCorner: 8,
    mainButtonStroke: "#e0e3e9",
    mainButtonBackground: "transparent",
    mainButtonLabel: "Claim your discount",
    mainButtonType: "cta-label-texticonl",
    mainButtonIcon: "pack-message-circle",

    triggerButtonFont: 'Varela Round',
    triggerButtonFontColor: '#333333',
    triggerButtonFontSize: 16,
    triggerButtonAlign: "right",
    triggerButtonWeight: '',
    triggerButtonItalic: '',
    triggerButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    triggerButtonCorner: 8,
    triggerButtonStroke: "#e0e3e9",
    triggerButtonBackground: "#eff3f6",
    triggerButtonLabel: "Click here for 10% off",
    triggerButtonType: "cta-label-texticonl",
    triggerButtonIcon: "pack-message-circle",

    textUsButtonNumber: '555888',
    textUsButtonText: '',
    textUsButtonFont: 'Varela Round',
    textUsButtonFontColor: '#333333',
    textUsButtonFontSize: 16,
    textUsButtonAlign: "right",
    textUsButtonWeight: '',
    textUsButtonItalic: '',
    textUsButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    textUsButtonCorner: 8,
    textUsButtonStroke: "#e0e3e9",
    textUsButtonBackground: "transparent",
    textUsButtonLabel: "",
    textUsButtonType: "cta-label-textonly",
    textUsButtonIcon: ""
  },
  {
    isPowered: true,
    folder: folder,
    size: 32,
    color: '#E67E78',
    font: 'BioRhyme',
    reason: 'Enter to win 1 year of free pet food! Text PAWPRINT to 900900.',
    reasonAlign: 'center',
    reasonWeight: 'bold',
    reasonItalic: '',
    secondarySize: 20,
    secondaryFont: 'Varela Round',
    secondaryColor: '#854523',
    secondaryReason: 'Text PAWPRINT to 900900. We’ll select a winner at random on 10/31/19. No purchase necessary. You’ll also be signed up for monthly updates on our new products.',
    secondaryReasonAlign: 'center',
    secondaryReasonWeight: '',
    secondaryReasonItalic: '',
    company: 'Your Company Name',
    estimated: 4,
    email: 'email@domain.com',
    customPrivacy: false,
    terms: '',
    privacy: '',
    complianceFont: 'Varela Round',
    complianceSize: 14,
    complianceColor: '#75849c',
    complianceAlign: 'left',
    complianceWeight: '',
    complianceItalic: '',
    logo: folder+'assets/templates/Ecommerce2_logo.svg',
    logoStyle: 'boxed',
    logoAlign: 'center',
    logoMaxWidth: 100,
    hyperlink: '',
    image: folder+'assets/templates/Ecommerce2_hero.png',
    imageWidth: 500,
    imageAlign: 'center',
    imageStyle: 'boxed',
    position: 'cta-boxed',
    colorA: '#75849C',
    stroke: '',
    background: '#FFFFFF',
    corner: 8,
    shadow: '0px 16px 64px rgba(0,0,0,0.08)',
    fontA: 'Varela Round',
    sizeA: 16,
    width: 500,
    closePosition: "cta-close-tr",
    keyword: '',
    phone: '',
    shortTerms: '',
    shortTermsPrivacy: '',
    shortPrivacy: '',

    mainButtonFont: 'Varela Round',
    mainButtonFontColor: '#333333',
    mainButtonFontSize: 16,
    mainButtonAlign: "center",
    mainButtonWeight: '',
    mainButtonItalic: '',
    mainButtonShadow: '0px 0px 0px rgba(0,0,0,0.0)',
    mainButtonCorner: 8,
    mainButtonStroke: "#e0e3e9",
    mainButtonBackground: "transparent",
    mainButtonLabel: "Enter now",
    mainButtonType: "cta-label-texticonl",
    mainButtonIcon: "pack-message-circle",

    triggerButtonFont: 'Varela Round',
    triggerButtonFontColor: '#333333',
    triggerButtonFontSize: 16,
    triggerButtonAlign: "right",
    triggerButtonWeight: '',
    triggerButtonItalic: '',
    triggerButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    triggerButtonCorner: 8,
    triggerButtonStroke: "#e0e3e9",
    triggerButtonBackground: "#eff3f6",
    triggerButtonLabel: "Click here to win free pet food",
    triggerButtonType: "cta-label-texticonl",
    triggerButtonIcon: "pack-message-circle",

    textUsButtonNumber: '555888',
    textUsButtonText: '',
    textUsButtonFont: 'Varela Round',
    textUsButtonFontColor: '#333333',
    textUsButtonFontSize: 16,
    textUsButtonAlign: "right",
    textUsButtonWeight: '',
    textUsButtonItalic: '',
    textUsButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    textUsButtonCorner: 8,
    textUsButtonStroke: "#e0e3e9",
    textUsButtonBackground: "transparent",
    textUsButtonLabel: "",
    textUsButtonType: "cta-label-textonly",
    textUsButtonIcon: ""
  },
  {
    isPowered: true,
    folder: folder,
    size: 32,
    color: '#367681',
    font: 'Playfair Display',
    reason: 'Get updates about our new arrivals. Text VINYL to 900900.',
    reasonAlign: 'center',
    reasonWeight: '',
    reasonItalic: '',
    secondarySize: 22,
    secondaryFont: 'Fira Sans',
    secondaryColor: '#6D7779',
    secondaryReason: 'Every week we add hundreds of rare LPs to our collection! Sign up for text updates to get a link sent to your phone as soon as they’re up for grabs.',
    secondaryReasonAlign: 'center',
    secondaryReasonWeight: '',
    secondaryReasonItalic: '',
    company: 'Your Company Name',
    estimated: 4,
    email: 'email@domain.com',
    customPrivacy: false,
    terms: '',
    privacy: '',
    complianceFont: 'Fira Sans',
    complianceSize: 14,
    complianceColor: '#75849c',
    complianceAlign: 'left',
    complianceWeight: '',
    complianceItalic: '',
    logo: folder+'assets/templates/Ecommerce3_logo.svg',
    logoStyle: 'boxed',
    logoAlign: 'center',
    logoMaxWidth: 51,
    hyperlink: '',
    image: folder+'assets/templates/rjK8ifDLnIk.png',
    imageWidth: 500,
    imageAlign: 'center',
    imageStyle: 'boxed',
    position: 'cta-boxed',
    colorA: '#75849C',
    stroke: '',
    background: '#FFFFFF',
    corner: 8,
    shadow: '0px 16px 64px rgba(0,0,0,0.08)',
    fontA: 'Fira Sans',
    sizeA: 16,
    width: 500,
    closePosition: "cta-close-tr",
    keyword: '',
    phone: '',
    shortTerms: '',
    shortTermsPrivacy: '',
    shortPrivacy: '',

    mainButtonFont: 'Fira Sans',
    mainButtonFontColor: '#333333',
    mainButtonFontSize: 16,
    mainButtonAlign: "center",
    mainButtonWeight: '',
    mainButtonItalic: '',
    mainButtonShadow: '0px 0px 0px rgba(0,0,0,0.0)',
    mainButtonCorner: 8,
    mainButtonStroke: "#e0e3e9",
    mainButtonBackground: "transparent",
    mainButtonLabel: "Sign up now",
    mainButtonType: "cta-label-texticonl",
    mainButtonIcon: "pack-message-circle",

    triggerButtonFont: 'Fira Sans',
    triggerButtonFontColor: '#333333',
    triggerButtonFontSize: 16,
    triggerButtonAlign: "right",
    triggerButtonWeight: '',
    triggerButtonItalic: '',
    triggerButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    triggerButtonCorner: 8,
    triggerButtonStroke: "#e0e3e9",
    triggerButtonBackground: "#eff3f6",
    triggerButtonLabel: "Click here for text updates",
    triggerButtonType: "cta-label-texticonl",
    triggerButtonIcon: "pack-message-circle",

    textUsButtonNumber: '555888',
    textUsButtonText: '',
    textUsButtonFont: 'Fira Sans',
    textUsButtonFontColor: '#333333',
    textUsButtonFontSize: 16,
    textUsButtonAlign: "right",
    textUsButtonWeight: '',
    textUsButtonItalic: '',
    textUsButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    textUsButtonCorner: 8,
    textUsButtonStroke: "#e0e3e9",
    textUsButtonBackground: "transparent",
    textUsButtonLabel: "",
    textUsButtonType: "cta-label-textonly",
    textUsButtonIcon: ""
  },
  {
    isPowered: true,
    folder: folder,
    size: 32,
    color: '#075167',
    font: 'Rubik',
    reason: 'Interested in a showing? Text 123MainSt to 41404.',
    reasonAlign: 'left',
    reasonWeight: '500',
    reasonItalic: '',
    secondarySize: 20,
    secondaryFont: 'Rubik',
    secondaryColor: '#C16A39',
    secondaryReason: 'Well-maintained 3-bed, 4-bath home with stainless steel appliances, hardwood floors, and cathedral ceilings.',
    secondaryReasonAlign: 'left',
    secondaryReasonWeight: '',
    secondaryReasonItalic: '',
    company: 'Your Company Name',
    estimated: 4,
    email: 'email@domain.com',
    customPrivacy: false,
    terms: '',
    privacy: '',
    complianceFont: 'Rubik',
    complianceSize: 14,
    complianceColor: '#75849c',
    complianceAlign: 'left',
    complianceWeight: '',
    complianceItalic: '',
    logo: folder+'assets/templates/Real_Estate_logo.svg',
    logoStyle: 'boxed',
    logoAlign: 'left',
    logoMaxWidth: 100,
    hyperlink: '',
    image: folder+'assets/templates/561igiTyvSk.png',
    imageWidth: 500,
    imageAlign: 'center',
    imageStyle: 'boxed',
    position: 'cta-boxed',
    colorA: '#75849C',
    stroke: '',
    background: '#FFFFFF',
    corner: 8,
    shadow: '0px 16px 64px rgba(0,0,0,0.08)',
    fontA: 'Rubik',
    sizeA: 16,
    width: 500,
    closePosition: "cta-close-tr",
    keyword: '',
    phone: '',
    shortTerms: '',
    shortTermsPrivacy: '',
    shortPrivacy: '',

    mainButtonFont: 'Rubik',
    mainButtonFontColor: '#333333',
    mainButtonFontSize: 16,
    mainButtonAlign: "center",
    mainButtonWeight: '',
    mainButtonItalic: '',
    mainButtonShadow: '0px 0px 0px rgba(0,0,0,0.0)',
    mainButtonCorner: 8,
    mainButtonStroke: "#e0e3e9",
    mainButtonBackground: "transparent",
    mainButtonLabel: "Schedule now",
    mainButtonType: "cta-label-texticonl",
    mainButtonIcon: "pack-message-circle",

    triggerButtonFont: 'Rubik',
    triggerButtonFontColor: '#333333',
    triggerButtonFontSize: 16,
    triggerButtonAlign: "right",
    triggerButtonWeight: '',
    triggerButtonItalic: '',
    triggerButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    triggerButtonCorner: 8,
    triggerButtonStroke: "#e0e3e9",
    triggerButtonBackground: "#eff3f6",
    triggerButtonLabel: "Schedule a showing",
    triggerButtonType: "cta-label-texticonl",
    triggerButtonIcon: "pack-message-circle",

    textUsButtonNumber: '555888',
    textUsButtonText: '',
    textUsButtonFont: 'Rubik',
    textUsButtonFontColor: '#333333',
    textUsButtonFontSize: 16,
    textUsButtonAlign: "right",
    textUsButtonWeight: '',
    textUsButtonItalic: '',
    textUsButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    textUsButtonCorner: 8,
    textUsButtonStroke: "#e0e3e9",
    textUsButtonBackground: "transparent",
    textUsButtonLabel: "",
    textUsButtonType: "cta-label-textonly",
    textUsButtonIcon: ""
  },
  {
    isPowered: true,
    folder: folder,
    size: 32,
    color: '#82051C',
    font: 'Crimson Text',
    reason: 'Text CHURCH to 94090 for our calendar of events ',
    reasonAlign: 'left',
    reasonWeight: '',
    reasonItalic: '',
    secondarySize: 18,
    secondaryFont: 'Roboto',
    secondaryColor: '#637289',
    secondaryReason: 'We’d love for you to join us at our next service! Text in now for a calendar of events and weekly updates about service opportunities.',
    secondaryReasonAlign: 'left',
    secondaryReasonWeight: '',
    secondaryReasonItalic: '',
    company: 'Your Company Name',
    estimated: 4,
    email: 'email@domain.com',
    customPrivacy: false,
    terms: '',
    privacy: '',
    complianceFont: 'Roboto',
    complianceSize: 14,
    complianceColor: '#75849c',
    complianceAlign: 'left',
    complianceWeight: '',
    complianceItalic: '',
    logo: folder+'assets/templates/Churches_logo.svg',
    logoStyle: 'boxed',
    logoAlign: 'left',
    logoMaxWidth: 140,
    hyperlink: '',
    image: folder+'assets/templates/QCjC1KpA4nA.png',
    imageWidth: 500,
    imageAlign: 'center',
    imageStyle: 'boxed',
    position: 'cta-boxed',
    colorA: '#75849C',
    stroke: '',
    background: '#FFFFFF',
    corner: 8,
    shadow: '0px 16px 64px rgba(0,0,0,0.08)',
    fontA: 'Roboto',
    sizeA: 16,
    width: 500,
    closePosition: "cta-close-tr",
    keyword: '',
    phone: '',
    shortTerms: '',
    shortTermsPrivacy: '',
    shortPrivacy: '',

    mainButtonFont: 'Roboto',
    mainButtonFontColor: '#333333',
    mainButtonFontSize: 16,
    mainButtonAlign: "center",
    mainButtonWeight: '',
    mainButtonItalic: '',
    mainButtonShadow: '0px 0px 0px rgba(0,0,0,0.0)',
    mainButtonCorner: 8,
    mainButtonStroke: "#e0e3e9",
    mainButtonBackground: "transparent",
    mainButtonLabel: "Get calendar",
    mainButtonType: "cta-label-texticonl",
    mainButtonIcon: "pack-message-circle",

    triggerButtonFont: 'Roboto',
    triggerButtonFontColor: '#333333',
    triggerButtonFontSize: 16,
    triggerButtonAlign: "right",
    triggerButtonWeight: '',
    triggerButtonItalic: '',
    triggerButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    triggerButtonCorner: 8,
    triggerButtonStroke: "#e0e3e9",
    triggerButtonBackground: "#eff3f6",
    triggerButtonLabel: "Interested in our next event?",
    triggerButtonType: "cta-label-texticonl",
    triggerButtonIcon: "pack-message-circle",

    textUsButtonNumber: '555888',
    textUsButtonText: '',
    textUsButtonFont: 'Roboto',
    textUsButtonFontColor: '#333333',
    textUsButtonFontSize: 16,
    textUsButtonAlign: "right",
    textUsButtonWeight: '',
    textUsButtonItalic: '',
    textUsButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    textUsButtonCorner: 8,
    textUsButtonStroke: "#e0e3e9",
    textUsButtonBackground: "transparent",
    textUsButtonLabel: "",
    textUsButtonType: "cta-label-textonly",
    textUsButtonIcon: ""
  },
  {
    isPowered: true,
    folder: folder,
    size: 32,
    color: '#683376',
    font: 'Poppins',
    reason: 'Win 2 tickets to see Scrantonicity! Text LIVE to (833) 602-8038.',
    reasonAlign: 'center',
    reasonWeight: '500',
    reasonItalic: '',
    secondarySize: 18,
    secondaryFont: 'Poppins',
    secondaryColor: '#000000',
    secondaryReason: 'Winner will be announced by text message on 11/1/12. No purchase necessary to enter.',
    secondaryReasonAlign: 'center',
    secondaryReasonWeight: '',
    secondaryReasonItalic: '',
    company: 'Your Company Name',
    estimated: 4,
    email: 'email@domain.com',
    customPrivacy: false,
    terms: '',
    privacy: '',
    complianceFont: 'Poppins Light',
    complianceSize: 14,
    complianceColor: '#75849c',
    complianceAlign: 'left',
    complianceWeight: '',
    complianceItalic: '',
    logo: folder+'assets/templates/Entertainment_logo.svg',
    logoStyle: 'boxed',
    logoAlign: 'center',
    logoMaxWidth: 64,
    hyperlink: '',
    image: folder+'assets/templates/ZhQCZjr9fHo.png',
    imageWidth: 500,
    imageAlign: 'center',
    imageStyle: 'boxed',
    position: 'cta-boxed',
    colorA: '#75849C',
    stroke: '',
    background: '#FFFFFF',
    corner: 8,
    shadow: '0px 16px 64px rgba(0,0,0,0.08)',
    fontA: 'Poppins Light',
    sizeA: 16,
    width: 500,
    closePosition: "cta-close-tr",
    keyword: '',
    phone: '',
    shortTerms: '',
    shortTermsPrivacy: '',
    shortPrivacy: '',

    mainButtonFont: 'Poppins Light',
    mainButtonFontColor: '#333333',
    mainButtonFontSize: 16,
    mainButtonAlign: "center",
    mainButtonWeight: '',
    mainButtonItalic: '',
    mainButtonShadow: '0px 0px 0px rgba(0,0,0,0.0)',
    mainButtonCorner: 8,
    mainButtonStroke: "#e0e3e9",
    mainButtonBackground: "transparent",
    mainButtonLabel: "Enter to win",
    mainButtonType: "cta-label-texticonl",
    mainButtonIcon: "pack-message-circle",

    triggerButtonFont: 'Poppins Light',
    triggerButtonFontColor: '#333333',
    triggerButtonFontSize: 16,
    triggerButtonAlign: "right",
    triggerButtonWeight: '',
    triggerButtonItalic: '',
    triggerButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    triggerButtonCorner: 8,
    triggerButtonStroke: "#e0e3e9",
    triggerButtonBackground: "#eff3f6",
    triggerButtonLabel: "Click here to win tickets",
    triggerButtonType: "cta-label-texticonl",
    triggerButtonIcon: "pack-message-circle",

    textUsButtonNumber: '555888',
    textUsButtonText: '',
    textUsButtonFont: 'Poppins Light',
    textUsButtonFontColor: '#333333',
    textUsButtonFontSize: 16,
    textUsButtonAlign: "right",
    textUsButtonWeight: '',
    textUsButtonItalic: '',
    textUsButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    textUsButtonCorner: 8,
    textUsButtonStroke: "#e0e3e9",
    textUsButtonBackground: "transparent",
    textUsButtonLabel: "",
    textUsButtonType: "cta-label-textonly",
    textUsButtonIcon: ""
  },
  {
    isPowered: true,
    folder: folder,
    size: 32,
    color: '#643121',
    font: 'Source Serif Pro',
    reason: 'Text SAVETREES to 56525 to find out about volunteer opportunities',
    reasonAlign: 'center',
    reasonWeight: 'bold',
    reasonItalic: '',
    secondarySize: 20,
    secondaryFont: 'Roboto Slab',
    secondaryColor: '#4B4043',
    secondaryReason: 'Help make a difference. Sign up for text alerts today to be the first to find out about exciting volunteer opportunities.',
    secondaryReasonAlign: 'center',
    secondaryReasonWeight: '',
    secondaryReasonItalic: '',
    company: 'Your Company Name',
    estimated: 4,
    email: 'email@domain.com',
    customPrivacy: false,
    terms: '',
    privacy: '',
    complianceFont: 'Roboto Slab',
    complianceSize: 14,
    complianceColor: '#75849c',
    complianceAlign: 'left',
    complianceWeight: '',
    complianceItalic: '',
    logo: folder+'assets/templates/Nonprofit_logo.svg',
    logoStyle: 'boxed',
    logoAlign: 'center',
    logoMaxWidth: 74,
    hyperlink: '',
    image: folder+'assets/templates/Nonprofit_hero.png',
    imageWidth: 500,
    imageAlign: 'center',
    imageStyle: 'boxed',
    position: 'cta-boxed',
    colorA: '#75849C',
    stroke: '',
    background: '#FFFFFF',
    corner: 8,
    shadow: '0px 16px 64px rgba(0,0,0,0.08)',
    fontA: 'Roboto Slab',
    sizeA: 16,
    width: 500,
    closePosition: "cta-close-tr",
    keyword: '',
    phone: '',
    shortTerms: '',
    shortTermsPrivacy: '',
    shortPrivacy: '',

    mainButtonFont: 'Roboto Slab',
    mainButtonFontColor: '#333333',
    mainButtonFontSize: 16,
    mainButtonAlign: "center",
    mainButtonWeight: '',
    mainButtonItalic: '',
    mainButtonShadow: '0px 0px 0px rgba(0,0,0,0.0)',
    mainButtonCorner: 8,
    mainButtonStroke: "#e0e3e9",
    mainButtonBackground: "transparent",
    mainButtonLabel: "Learn more",
    mainButtonType: "cta-label-texticonl",
    mainButtonIcon: "pack-message-circle",

    triggerButtonFont: 'Roboto Slab',
    triggerButtonFontColor: '#333333',
    triggerButtonFontSize: 16,
    triggerButtonAlign: "right",
    triggerButtonWeight: '',
    triggerButtonItalic: '',
    triggerButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    triggerButtonCorner: 8,
    triggerButtonStroke: "#e0e3e9",
    triggerButtonBackground: "#eff3f6",
    triggerButtonLabel: "Volunteer with us",
    triggerButtonType: "cta-label-texticonl",
    triggerButtonIcon: "pack-message-circle",

    textUsButtonNumber: '555888',
    textUsButtonText: '',
    textUsButtonFont: 'Roboto Slab',
    textUsButtonFontColor: '#333333',
    textUsButtonFontSize: 16,
    textUsButtonAlign: "right",
    textUsButtonWeight: '',
    textUsButtonItalic: '',
    textUsButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
    textUsButtonCorner: 8,
    textUsButtonStroke: "#e0e3e9",
    textUsButtonBackground: "transparent",
    textUsButtonLabel: "",
    textUsButtonType: "cta-label-textonly",
    textUsButtonIcon: ""
  },
  // {
  //   isPowered: true,
  //   folder: folder,
  //   size: 32,
  //   color: '#0068B8',
  //   font: 'Open Sans',
  //   reason: 'Text DEMO to 555888',
  //   reasonAlign: 'center',
  //   reasonWeight: 'bold',
  //   reasonItalic: '',
  //   secondarySize: 20,
  //   secondaryFont: 'Rubik',
  //   secondaryColor: '#75849C',
  //   secondaryReason: 'We’ll send you a quick video that shows you how to use this tool to grow your subscriber list.',
  //   secondaryReasonAlign: 'center',
  //   secondaryReasonWeight: '',
  //   secondaryReasonItalic: '',
  //   company: 'Your Company Name',
  //   estimated: 4,
  //   email: 'email@domain.com',
  //   customPrivacy: false,
  //   terms: '',
  //   privacy: '',
  //   complianceFont: 'Rubik',
  //   complianceSize: 14,
  //   complianceColor: '#75849c',
  //   complianceAlign: 'left',
  //   complianceWeight: '',
  //   complianceItalic: '',
  //   logo: folder+'assets/templates/CTA-SimpleTexting_logo.png',
  //   logoStyle: 'boxed',
  //   logoAlign: 'center',
  //   logoMaxWidth: 192,
  //   hyperlink: '',
  //   image: folder+'assets/templates/CTA-SimpleTexting_hero.png',
  //   imageWidth: 500,
  //   imageAlign: 'center',
  //   imageStyle: 'boxed',
  //   position: 'cta-boxed',
  //   colorA: '#75849C',
  //   stroke: '',
  //   background: '#FFFFFF',
  //   corner: 8,
  //   shadow: '0px 16px 64px rgba(0,0,0,0.08)',
  //   fontA: 'Rubik',
  //   sizeA: 16,
  //   width: 500,
  //   closePosition: "cta-close-tr",
  //   keyword: '',
  //   phone: '',
  //   shortTerms: '',
  //   shortTermsPrivacy: '',
  //   shortPrivacy: '',

  //   mainButtonFont: 'Rubik',
  //   mainButtonFontColor: '#333333',
  //   mainButtonFontSize: 16,
  //   mainButtonAlign: "center",
  //   mainButtonWeight: '',
  //   mainButtonItalic: '',
  //   mainButtonShadow: '0px 0px 0px rgba(0,0,0,0.0)',
  //   mainButtonCorner: 8,
  //   mainButtonStroke: "#e0e3e9",
  //   mainButtonBackground: "transparent",
  //   mainButtonLabel: "",
  //   mainButtonType: "cta-label-texticonl",
  //   mainButtonIcon: "pack-message-circle",

  //   triggerButtonFont: 'Rubik',
  //   triggerButtonFontColor: '#333333',
  //   triggerButtonFontSize: 16,
  //   triggerButtonAlign: "right",
  //   triggerButtonWeight: '',
  //   triggerButtonItalic: '',
  //   triggerButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
  //   triggerButtonCorner: 8,
  //   triggerButtonStroke: "#e0e3e9",
  //   triggerButtonBackground: "#eff3f6",
  //   triggerButtonLabel: "",
  //   triggerButtonType: "cta-label-texticonl",
  //   triggerButtonIcon: "pack-message-circle",

  //   textUsButtonNumber: '555888',
  //   textUsButtonText: '',
  //   textUsButtonFont: 'Rubik',
  //   textUsButtonFontColor: '#333333',
  //   textUsButtonFontSize: 16,
  //   textUsButtonAlign: "right",
  //   textUsButtonWeight: '',
  //   textUsButtonItalic: '',
  //   textUsButtonShadow: '0px 16px 64px rgba(0,0,0,0.08)',
  //   textUsButtonCorner: 8,
  //   textUsButtonStroke: "#e0e3e9",
  //   textUsButtonBackground: "transparent",
  //   textUsButtonLabel: "",
  //   textUsButtonType: "cta-label-textonly",
  //   textUsButtonIcon: ""
  // }
]